cursor #e7e1e3
cursor_text_color #cac5c7

foreground            #e7e1e3
background            #141314
selection_foreground  #352e36
selection_background  #cec3cd
url_color             #d1c2d2

color0   #141314
color1   #f16c7d
color2   #69d285
color3   #ffdd72
color4   #c6b5c7
color5   #605361
color6   #d1c2d2
color7   #dbcfdc
color8   #877e88
color9   #ff9fab
color10  #a3fbbc
color11  #ffe9a5
color12  #e6d8e7
color13  #fef1ff
color14  #fef6ff
color15  #fef8ff
