cursor #e5e1e3
cursor_text_color #c9c6c7

foreground            #e5e1e3
background            #131315
selection_foreground  #2f3038
selection_background  #c7c5d0
url_color             #c5c5d6

color0   #131315
color1   #f66e8f
color2   #6bd67e
color3   #ffd872
color4   #b7b7cb
color5   #545463
color6   #c5c5d6
color7   #d3d3e0
color8   #80808b
color9   #ff9fb6
color10  #a5ffb5
color11  #ffe6a5
color12  #dbdbeb
color13  #f0f0ff
color14  #f5f5ff
color15  #f8f8ff
