-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", mode = "1920x1080@60.16", position = "-3200x0", scale = 1.50 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.00", position = "-1920x-544", scale = 1.00 })
